const defaultData = {
  anakritikoi: ["Αρχ/κα ΠΑΠΠΑ Ιωάννη", "Ανθ/μου ΠΑΠΑΔΟΠΟΥΛΟΥ Αλέξιου"],
  anakritikoiEnikos: ["Αρχ/κας ΠΑΠΠΑΣ Ιωάννης", "Ανθ/μος ΠΑΠΑΔΟΠΟΥΛΟΣ Αλέξιος"],
  ypiresia: "Τ.Δ.Ε.Ε. Κομοτηνής",
  doy: "Κομοτηνής",
  merosSyntaksisEkthesis: "Κομοτηνή",
  xronosPeratosis: 10,
  eisaggeleiaProtodikon: "Ροδόπης",
  dieuthynsiYpiresias: "Λ Δημοκρατίας αρ. 3",
  tilefono: "25314 40177",
  email: "tdee.komotinis@astynomia.gr",
  dAstynomias: "ΡΟΔΟΠΗΣ",
  geniki: "Α.Μ.Θ.",
  iatro: "ΡΟΔΟΠΗΣ",
  amy: "4587",
};
const months = [
  "Ιανουαρίου",
  "Φεβρουαρίου",
  "Μαρτίου",
  "Απριλίου",
  "Μαΐου",
  "Ιουνίου",
  "Ιουλίου",
  "Αυγούστου",
  "Σεπτεμβρίου",
  "Οκτωβρίου",
  "Νοεμβρίου",
  "Δεκεμβρίου",
];

const days = [
  "Κυριακή",
  "Δευτέρα",
  "Τρίτη",
  "Τετάρτη",
  "Πέμπτη",
  "Παρασκευή",
  "Σάββατο",
];
const dikografies = {
  drugs: [
    "martyra",
    "katasxesi",
    "syllipsi",
    "gnostopoiisi",
    "katigoroumenou",
    "praktikoZygisis",
    "gnostopoiisiNarkwtikwn",
    "ypoptoy",
    "feromenou",
  ],
  // endo: [
  //   "martyra-endooik",
  //   "thyma-endooik",
  //   "syllipsiEndo",
  //   "drastis-endooik",
  //   "iatrodikastiki-endooik",
  //   "panicYes",
  //   "panicNo",
  //   "afairesi",
  //   "katasxesiEndo",
  //   "ypoptoyEndo",
  //   "simansi",
  //   "vasEndo",
  //   "dioksiEndo",
  //   "drastisEndo",
  //   "iatrodikEndo",
  //   "oploEndo",
  //   "ypotroposEndo",
  //   "autoforoEndo",
  //   "protokEndo",
  //   "ypovoliEndo",
  //   "apostoliEndo",
  // ],
};
export { defaultData, months, days, dikografies };
