const defaultData = {
  anakritikoi: ["Αρχ/κα ΠΑΠΠΑ Ιωάννη", "Ανθ/μου ΠΑΠΑΔΟΠΟΥΛΟΥ Αλέξιου"],
  anakritikoiEnikos: ["Αρχ/κας ΠΑΠΠΑΣ Ιωάννης", "Ανθ/μος ΠΑΠΑΔΟΠΟΥΛΟΣ Αλέξιος"],
  ypiresia: "Τ.Δ.Ε.Ε. Κομοτηνής",
  doy: "Κομοτηνής",
  merosSyntaksisEkthesis: "Κομοτηνή",
  xronosPeratosis: 10,
  eisaggeleiaProtodikon: "Ροδόπης",
  dieuthynsiYpiresias: "Λ Δημοκρατίας αρ. 3",
  tilefono: "25314 40177",
  email: "tdee.komotinis@astynomia.gr",
  dAstynomias: "ΡΟΔΟΠΗΣ",
  geniki: "Α.Μ.Θ.",
  iatro: "ΡΟΔΟΠΗΣ",
  amy: "4587",
  dioikitisName: "",
  dioikitisRank: "",
  dioikitisSex: "Άντρας",
};
const months = [
  "Ιανουαρίου",
  "Φεβρουαρίου",
  "Μαρτίου",
  "Απριλίου",
  "Μαΐου",
  "Ιουνίου",
  "Ιουλίου",
  "Αυγούστου",
  "Σεπτεμβρίου",
  "Οκτωβρίου",
  "Νοεμβρίου",
  "Δεκεμβρίου",
];
// months is genitive, for "του μήνα Σεπτεμβρίου"; form fields labelled "Μήνας" need nominative
const monthsNominative = [
  "Ιανουάριος",
  "Φεβρουάριος",
  "Μάρτιος",
  "Απρίλιος",
  "Μάιος",
  "Ιούνιος",
  "Ιούλιος",
  "Αύγουστος",
  "Σεπτέμβριος",
  "Οκτώβριος",
  "Νοέμβριος",
  "Δεκέμβριος",
];

const days = [
  "Κυριακή",
  "Δευτέρα",
  "Τρίτη",
  "Τετάρτη",
  "Πέμπτη",
  "Παρασκευή",
  "Σάββατο",
];
const defaultAstynomikos = `ΒΑΘΜΟΣ ΕΠΙΘΕΤΟ Όνομα, γεν ΗΗ/ΜΜ/ΧΧΧΧ στην ΤΟΠΟΣ ΓΕΝ, κάτοικος ${defaultData.merosSyntaksisEkthesis}, οδός ${defaultData.dieuthynsiYpiresias}, κάτοχος του υπ'αριθμ. 222333 Υπηρεσιακού Δελτίου Ταυτότητας, εκδοθέν το 2025 από ΕΛ.ΑΣ, με ΑΦΜ 111222333 / Δ.Ο.Υ ${defaultData.doy}, επαγγέλματος Αστυνομικός, χρήστης της υπ'αριθμ. ${defaultData.tilefono} τηλεφωνικής σύνδεσης και της ${defaultData.email} διεύθυνσης ηλεκτρονικής αλληλογραφίας`;
const dikografies = {
  drugs: [
    "martyra",
    "katasxesi",
    "syllipsi",
    "gnostopoiisi",
    "katigoroumenou",
    "praktikoZygisis",
    "gnostopoiisiNarkwtikwn",
    "ypoptoy",
    "feromenou",
  ],
  // endo: [
  //   "martyra-endooik",
  //   "thyma-endooik",
  //   "syllipsiEndo",
  //   "drastis-endooik",
  //   "iatrodikastiki-endooik",
  //   "panicBtn",
  //   "panicEndo",
  //   "afairesi",
  //   "katasxesiEndo",
  //   "ypoptoyEndo",
  //   "simansi",
  //   "vasEndo",
  //   "dioksiEndo",
  //   "drastisEndo",
  //   "iatrodikEndo",
  //   "oploEndo",
  //   "ypotroposEndo",
  //   "autoforoEndo",
  //   "protokEndo",
  //   "endoOptions",
  //   "ypovoliEndo",
  //   "apostoliEndo",
  // ],
};
export {
  defaultData,
  months,
  monthsNominative,
  days,
  dikografies,
  defaultAstynomikos,
};
